apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-app
  labels:
    app: configserver-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver-app
  template:
    metadata:
      labels:
        app: configserver-app
    spec:
      containers:
        - name:  configserver-app
          image: adama93/configserver:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9296

---
apiVersion: v1
kind: Service
metadata:
  name: configserver-svc
spec:
  ports:
    - targetPort: 9296
      port: 80
  selector:
    app: configserver-app